In [74]:
import os

import numpy as np
import pandas as pd

from src import dataset

In [75]:
X_dict, y_dict, list_features = dataset.create_dataset(path_to_files='C:\\Users\\Mariana\\PycharmProjects\\epilepsy-2022\\data', str_files='level2_features')
X = np.array(list(X_dict.values()))
y = np.array(list(y_dict.values()))

C:\Users\Mariana\AppData\Local\Temp\ipykernel_18200\3722300735.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X = np.array(list(X_dict.values()))
C:\Users\Mariana\AppData\Local\Temp\ipykernel_18200\3722300735.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  y = np.array(list(y_dict.values()))


In [76]:
y

array([array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
              1., 1., 1., 1., 1., 1., 1., 1., 1.])                               ,
       array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
              0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
              1., 1.])                                                           ,
       array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
              0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
              0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]),
       array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
              1., 1., 1., 1.])                                                   ,
       array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
              0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           

In [78]:
# datasets leave 2 patients out
from sklearn.model_selection import LeavePOut
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report

lpo = LeavePOut(p=1)

selected_features = ['meanrr-min', 'meanrr-trend_ratio']
selected_features_idx = [idx for idx, feature in enumerate(list_features) if feature in selected_features]
print(selected_features_idx)

def kfold_eval(selected_features_idx):
    for train_idx, test_idx in lpo.split(X):
        print(np.array(list(X_dict.keys()))[test_idx])
        X_train, X_test = np.vstack(X[train_idx])[:, selected_features_idx], np.vstack(X[test_idx])[:, selected_features_idx]
        y_train, y_test = np.hstack(y[train_idx]), np.hstack(y[test_idx])
        gnb = GaussianNB()
        y_pred = gnb.fit(X_train, y_train).predict(X_test)
        cr = classification_report(y_pred, y_test)
        print(cr)
    return cr

cr = kfold_eval(selected_features_idx)





[0, 124]
['p312']
              precision    recall  f1-score   support

         0.0       0.12      1.00      0.22         2
         1.0       1.00      0.42      0.59        24

    accuracy                           0.46        26
   macro avg       0.56      0.71      0.41        26
weighted avg       0.93      0.46      0.56        26

['p326']
              precision    recall  f1-score   support

         0.0       0.33      0.90      0.49        10
         1.0       0.89      0.31      0.46        26

    accuracy                           0.47        36
   macro avg       0.61      0.60      0.47        36
weighted avg       0.73      0.47      0.47        36

['p352']
              precision    recall  f1-score   support

         0.0       0.08      1.00      0.15         4
         1.0       1.00      0.02      0.04        47

    accuracy                           0.10        51
   macro avg       0.54      0.51      0.09        51
weighted avg       0.93      0.10     